### PR TITLE
svg file for project icon & Upper Bound Charge Notification

### PR DESCRIPTION
**Pull request by 22shubh22**
# Description

Made a svg file for as icon of this prject

Fixes # (issue)

#72 

Please delete options that are not relevant.

- [x] This is just a svg file.
- [x]  The PR does not include change in code to display svg icon in tray instead of png icon.

### CODE REVIEW

**Comment by maateen** [comment]
@yochananmarqos can you please review this PR?

**Comment by 22shubh22** [comment]
commit d1432b9 contains the addition of Upper threshold warning ( see issue #81 ).

**Comment by maateen** [comment]
@22shubh22 Thanks a lot for your contribution. @yochananmarqos or @benley can you guys help to review this PR?

**Comment by yochananmarqos** [comment]
This needs a little more work, I think. I just turned on my laptop while connected to the charger and I started getting an Upper Threshold Warning at 5%. The setting is the default 90%.

**Pull request merged**
