### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by yochananmarqos**
Added AUR link to the stable version

### CODE REVIEW

**Comment by yochananmarqos** [comment]
Your README is out of date, can you accept this? The stable version is now in the AUR and the beta has a different package name.

**Comment by maateen** [comment]
@yochananmarqos Thanks for PR. Can you please look into some open issues? My Linux machine has been theft and I'm out of the support.

**Comment by yochananmarqos** [comment]
Sure, I'll see what I can do.

**Comment by maateen** [comment]
Thanks, man. Also, please upload some new screenshots of the new version if you can.

**Pull request merged**
