### PR TITLE
multiple battery support

### PR DESCRIPTION
**Pull request by tocomo**
at least multiple batteries listed wont break the tool:

acpi -b
Battery 0: Full, 100%
Battery 1: Discharging, 0%, rate information unavailable

### CODE REVIEW

**Comment by tocomo** [comment]
now it works with ubuntu 18.04 too.

**Comment by maateen** [comment]
@tocomo thanks a lot for your effort. Can you please make necessary changes in **devel** branch and give PR to **devel** branch? Our beta testers can test that branch and we can merge to master after that.

**Comment by tocomo** [comment]
The devel branch containes my fix already :-)

**Comment by maateen** [comment]
@tocomo In that case, can you please test the **devel** branch and express your valuable comment?

**Comment by tocomo** [comment]
That means having more then one battery slot won't break execution anymore if devel branch is used. So fare so good. I have a lot of other thing to complain about - but that are different topics.

**Comment by maateen** [comment]
@tocomo Thanks a lot for your input. Please never hesitate to share your thoughts, if possible, please send us PR for the solution of those complain.

**Pull request closed without merging**
