### PR TITLE
Fix misc bugs and problems + enhance the code

### PR DESCRIPTION
**Pull request by abougouffa**

### CODE REVIEW

**Comment by maateen** [comment]
This branch has conflicts that must be resolved. Please fix the conflicts if you can. I am sorry if this happens for my recent change in structure. Also check our new branch **devel**. I recommend to push code to that branch. Once the change is stable, we can merge them with **master** branch.

**Comment by abougouffa** [comment]
Ok @maateen, I will fix it.

**Comment by abougouffa** [comment]
It's done, you can merge it now! I will push the future works to the **devel** 👍 

Have a nice day 😄

**Comment by maateen** [comment]
Thanks for your contribution in this project. I am busy right now with other things so I am away. Please take a look at [roadmap](https://github.com/maateen/battery-monitor#roadmap) and try to follow/change. Also pay attention at [v0.5 milestone](https://github.com/maateen/battery-monitor/milestone/1).

Have a nice day my friend. :smiley:

**Comment by abougouffa** [comment]
Ok friend,
When I get some free time I will try to work on this guidelines.

Best regards,
Abdelhak

**Pull request merged**
