### PR TITLE
Add setup.py, become a regular Python package, improve Makefile

### PR DESCRIPTION
**Pull request by benley**
This ought to make life somewhat easier for anyone packaging battery-monitor for a new linux distribution, and for developers familiar with a typical Python dev workflow.

### CODE REVIEW

**Comment by maateen** [comment]
@benley Awesome work man. Can you please do three things:

1.  Is it PPA compatible? I mean. can we push it to PPA easily?
2. This project isn't Ubuntu 16.04 compatible as that uses Python 3.5.x for default Python3. Can you please look into this?
3. Please add your name to the contributor list.

**Comment by benley** [comment]
1 and 2: Where is the Debian packaging metadata for this project kept?  I see the PPA at https://launchpad.net/~maateen/+archive/ubuntu/battery-monitor but I don't know where the /debian directory is kept in version control, if anywhere.

**Comment by maateen** [comment]
@benley we used separate repo for this purposes.

**Comment by yochananmarqos** [comment]
It installs and runs fine, except it does not copy battery-monitor.png to /usr/share/pixmaps.

**Comment by yochananmarqos** [comment]
I also found and issue uninstalling it:
```
$ sudo make uninstall
[sudo] password for yochanan: 
You must be root to uninstall.
rm -f /etc/xdg/autostart/battery-monitor-autostart.desktop
rm -f /usr/share/applications/battery-monitor.desktop
tr '\n' '\0' installed-files.txt | xargs -0 rm -fvd --
tr: extra operand ‘installed-files.txt’
Try 'tr --help' for more information.
make: *** [Makefile:32: uninstall] Error 1
```

**Comment by benley** [comment]
Would anyone object to simply removing the `uninstall` target from the Makefile? It is uncommon to see Makefiles try to do this; usually uninstalling is safer left to a package manager.

**Comment by yochananmarqos** [comment]
@benley I agree.

**Comment by benley** [comment]
I think I've made all the requested changes:
- Added myself to the contributors list
- Fixed the missing `/usr/share/pixmaps/battery-monitor.png`
- Removed the uninstall target
- Added trove classifiers to setup.py to express the Python >= 3.6 requirement

**Comment by benley** [comment]
and I rebased my branch so the individual commits are more coherent.  This PR should be ready for another look now.

**Comment by maateen** [comment]
@benley Awesome work man. We highly appreciate your work.

Is README.md updated enough for installation regarding the new structure?

**Comment by benley** [comment]
> Is README.md updated enough for installation regarding the new structure?

Ooh good point.  I've just added a mention of the new `setuptools` dependency to README.md.  The install steps for users have not changed, so the rest should still be OK.

**Comment by maateen** [comment]
Thanks a lot, man. Welcome to the contributor family.

**Pull request merged**
