### PR TITLE
Reformatting and optimized code

### PR DESCRIPTION
**Pull request by safwanrahman**

### CODE REVIEW

**Comment by maateen** [comment]
This pull request implements `upower` instead of `acpi -b`. Let's show the world some benchmark tests:

>When I run the script for 33.27 s

```
	Command being timed: "python3 battery-monitor.py"
	User time (seconds): 10.09
	System time (seconds): 4.69
	Percent of CPU this job got: 44%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:33.27
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 32568
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 1618183
	Voluntary context switches: 130592
	Involuntary context switches: 12629
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

Not only that, at the time of running this script, a new command `/usr/bin/dbus -daemon...` run all time that use about **22%** CPU on my PC. :cry: The previous command actually triggered by `upower`. So think over it.

**Comment by safwanrahman** [comment]
I have made more optimization and the result is following

```bash
	Command being timed: "python battery-monitor.py"
	User time (seconds): 0.09
	System time (seconds): 0.01
	Percent of CPU this job got: 0%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:17.31
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 30892
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 7456
	Voluntary context switches: 324
	Involuntary context switches: 20
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

**Comment by maateen** [comment]
Now it's okay. But remove line **47** from `battery-monitor.py`.

**Comment by safwanrahman** [comment]
> Remove print statement.

ha ha ha ha ha. Just a papercut.

**Comment by safwanrahman** [comment]
Updated!

**Comment by maateen** [comment]
@safwanrahman Check my latest commit, some change made. You have messed up Gtk.

**Comment by safwanrahman** [comment]
Oh, I did not notice. I dont have much idea about Gtk and others.
[This commit maybe](https://github.com/maateen/battery-monitor/blob/d357df102cca6cd15d4a6dfc5e78cbcb5c565fa5)

**Comment by maateen** [comment]
I fix it. No problem. You have done a great job. Proud of you.

>Contributors

>[Safwan Rahman](https://github.com/safwanrahman)

>One of the biggest contributor of **Battery Monitor**. He has reformated the code in a new style. The style represents the code easier to understand. Also he has optimized the code in a way that **Battery Monitor** consumes a little resource of your PC. Please take a minute to thank him.

**Pull request merged**
